from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
	return LaunchDescription([
		Node(
			package='cv_basics',
			executable='image_subscriber',
			name='sub',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub1',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub2',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub3',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub4',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub5',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub6',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub7',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub8',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub9',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub10',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub11',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub12',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub13',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub14',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub15',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub16',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub17',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub18',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub19',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub20',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub21',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub22',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub23',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub24',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub25',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub26',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub27',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub1',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub2',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub3',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub4',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub5',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub6',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub7',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub8',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub9',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub10',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub11',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub12',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub13',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub14',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub15',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub16',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub17',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub18',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub19',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub20',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub21',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub22',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub23',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub24',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub25',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub26',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub27',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub1',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub2',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub3',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub4',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub5',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub6',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub7',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub8',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub9',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub10',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub11',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub12',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub13',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub14',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub15',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub16',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub17',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub18',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub19',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub20',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub21',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub22',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub23',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub24',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub25',
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub26',	
			output='screen'
		),
		Node(
			package='cv_basics',
			namespace='publisher',
			executable='image_publisher',
			name='pub27',
			output='screen'
		)
	])
